#!/usr/bin/env php
<?php
if(!array_key_exists(1, $argv)){
    die("First argument must be the name of the executable\n");
}

$pharFile = __DIR__ . '/' . $argv[1] . '.phar';

// clean up
if (file_exists($pharFile))
{
	unlink($pharFile);
}

if (file_exists($pharFile . '.gz'))
{
	unlink($pharFile . '.gz');
}

// create phar
$f = basename($pharFile);
var_dump($f);
$phar = new Phar($f);

// start buffering. Mandatory to modify stub to add shebang
//$phar->startBuffering();

// Create the default stub from main.php entrypoint
$defaultStub = $phar->createDefaultStub('main.php');

// Add the rest of the apps files
$phar->buildFromDirectory(__DIR__ . '/src', '/\.php$/');

// Customize the stub to add the shebang
$stub = "#!/usr/bin/env php \n" . $defaultStub;

// Add the stub
$phar->setStub($stub);

//$phar->stopBuffering();

// plus - compressing it into gzip  
$phar->compressFiles(Phar::GZ);

# Make the file executable
$filename = str_replace('.phar', '', $pharFile);
chmod($pharFile, 0770);
//copy($pharFile, $filename);

echo basename($filename) . " successfully created" . PHP_EOL;
